### ISSUE TITLE
Check project compatibility with Visual Studio

### ISSUE THREAD

**Issue by HenryWConklin** [HenryWConklin/Blink#1]
I created the project in MonoDevelop on Ubuntu, make sure it works with other configurations e.g. Visual Studio on Windows and MonoDevelop or whatever on Mac

**Comment by HenryWConklin** [comment]
@Curlystraw Ok, now it looks like the project is compatible with nothing but visual studio on windows

**Comment by Curlystraw** [comment]
Oh. Crud, My project was DirectX I think. It'll have to be refactored into OpenGL.

**Comment by HenryWConklin** [comment]
Well, I've messed with it a bit and can't get it working. I do have windows as well, so I'm fine if we have to develop on windows, but we probably should get it switched to OpenGL for those on macs.

**Comment by HenryWConklin** [comment]
Ok, crossPlatform branch seems to work on both linux and windows. Can someone else verify that it works for them on windows?

**Comment by alamb93** [comment]
It doesn't seem to be working for me. I am getting this error. I am running it in Visual Studio on Windows. Error:"An unhandled exception of type 'System.DllNotFoundException' occurred in Tao.Sdl.dll"
Additional information: Unable to load DLL 'SDL.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by HenryWConklin** [comment]
Did you not need the dlls before? It should ask for a couple sdl related
things, you just need to put them in the folder with the executable. If
that's too much of a hassle I can mess with it some more.

**Comment by alamb93** [comment]
It already seems to be in the same folder as the executable, it just doesn't seem to find it. I think it is searching in another location. Previously, Tao.Sdl.dll was in another folder within the packages folder. I will move things around to see if that is the issue.

**Comment by alamb93** [comment]
Scratch that. The dll is also showing up in the folder with executable as well with the past projects so I am not quite sure why it isn't finding it. I can do some more looking around to see if I find the problem.

**Comment by HenryWConklin** [comment]
Did you ever get it working?

**Comment by HenryWConklin** [comment]
Wait, I just changed one line on master and it worked. Try the new commit

**Comment by alamb93** [comment]
Everything seems fine now. Thank!

**Comment by HenryWConklin** [comment]
Awesome
